'use client';
import { useAppContext } from "@/context/app-context";
import { useIntl } from "react-intl";
import NamerUiBadge from "./namer-ui-badge";
import React from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Separator } from "./ui/separator";

type TextPart = {
  text: string;
  isLink: boolean;
  link?: { href: string; text: string };
};

type LanguageStrings = {
  line: TextPart[];
};

// Basic sanitization: allow only http(s) links
function sanitizeUrl(url: string): string | null {
  try {
    const parsed = new URL(url);
    if (parsed.protocol === "http:" || parsed.protocol === "https:") {
      return url;
    }
    return null;
  } catch {
    return null;
  }
}

const Credits = () => {
    const intl = useIntl();
    const isRTL = intl.locale === 'he';

    const creditsMarkdown = `
[Resizable Navbar](https://ui.aceternity.com/components/resizable-navbar) by [Aceternity UI](https://ui.aceternity.com/)

[BUTTONS](https://codepen.io/uchihaclan/pen/NWOyRWy) by [TAYLOR](https://codepen.io/uchihaclan)

[Wheel Picker](https://21st.dev/ncdai/wheel-picker/default) by [Chánh Đại](https://21st.dev/ncdai)

[React Wheel Picker](https://www.npmjs.com/package/@ncdai/react-wheel-picker) by [Chánh Đại](https://github.com/ncdai)

[すりガラスなプロフィールカード](https://codepen.io/ash_creator/pen/zYaPZLB) by [あしざわ - Webクリエイター](https://codepen.io/ash_creator)

[framer-motion](https://www.npmjs.com/package/framer-motion)

[motion](https://www.npmjs.com/package/motion)

[AnimateIcons](https://animateicons.vercel.app/)

[i18next](https://www.npmjs.com/package/i18next)

[three.js](https://www.npmjs.com/package/three)

[Lucide React](https://www.npmjs.com/package/lucide-react)

[Gooey Text Morphing](https://21st.dev/victorwelander/gooey-text-morphing/default) by [Victor Welander](https://21st.dev/victorwelander)

[Morphing Text](https://21st.dev/dillionverma/morphing-text/default) by [Magic UI](https://21st.dev/magicui)

[Bento Grid](https://ui.aceternity.com/components/bento-grid) by [Aceternity UI](https://ui.aceternity.com/)

[Custom Checkbox](https://21st.dev/Edil-ozi/custom-checkbox/default) by [Edil Ozi](https://21st.dev/Edil-ozi)

[チェックしないと押せないボタン](https://codepen.io/ash_creator/pen/JjZReNm) by [あしざわ - Webクリエイター](https://codepen.io/ash_creator)

[Coach Scheduling Card](https://21st.dev/isaiahbjork/coach-scheduling-card/default) by [Isaiah](https://21st.dev/isaiahbjork)

[Calendar](https://21st.dev/designali-in/calendar/default) by [Ali Imam](https://21st.dev/dalim)

[react-swipeable](https://www.npmjs.com/package/react-swipeable)

[Input Floating Label animation](https://codepen.io/Mahe76/pen/qBQgXyK) by [Elpeeda](https://codepen.io/Mahe76)

[radix-ui](https://www.npmjs.com/package/radix-ui)

App logo is generated by [Craiyon](https://www.craiyon.com/en/image/RG_r3zVbS523AfTiQqHIew)
`;

    function renderEntry(entry: string) {
        const regex = /\[([^\]]+)\]\(([^)]+)\)/g;
        const parts: React.ReactNode[] = [];
        let lastIndex = 0;
        let match: RegExpExecArray | null;
        let key = 0;

        while ((match = regex.exec(entry)) !== null) {
            if (match.index > lastIndex) {
                parts.push(<span key={key++}>{entry.slice(lastIndex, match.index)}</span>);
            }
            let label = match[1];
            parts.push(
                <a key={key++} href={match[2]} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
                    {label}
                </a>
            );
            lastIndex = regex.lastIndex;
        }

        if (lastIndex < entry.length) {
            parts.push(<span key={key++}>{entry.slice(lastIndex)}</span>);
        }
        return parts;
    }

    const creditEntries = creditsMarkdown.trim().split('\n').map(e => e.trim()).filter(Boolean);

    return (
        <Card className="bg-transparent border-0 shadow-none">
            <CardHeader className="p-4" style={{ textAlign: isRTL ? 'right' : 'left' }}>
                <CardTitle className="text-xl">{intl.formatMessage({ id: 'footer.creditTitle' })}</CardTitle>
                <CardDescription style={{ direction: isRTL ? 'rtl' : 'ltr' }}>{intl.formatMessage({ id: 'footer.creditDescription' })}</CardDescription>
            </CardHeader>
            <CardContent className="p-4 pt-0 flex flex-col items-start gap-6 h-auto" dir={isRTL ? 'rtl' : 'ltr'}>
                <ul style={{ listStyleType: "none", padding: 0, margin: 0, lineHeight: 1.75, textAlign: isRTL ? "right" : "left", direction: isRTL ? "rtl" : "ltr", alignSelf: isRTL ? 'flex-end' : 'flex-start' }}>
                    {creditEntries.map((entry, idx) => (
                        <li key={idx} style={{ marginBottom: idx === creditEntries.length - 1 ? 0 : 20, wordWrap: "break-word", wordBreak: "break-word", whiteSpace: "normal", fontSize: "1rem" }}>
                            {renderEntry(entry)}
                        </li>
                    ))}
                </ul>
            </CardContent>
        </Card>
    );
};


export function AppFooter() {
  const { locale } = useAppContext();
  const intl = useIntl();
  const t = (id: string) => intl.formatMessage({ id });
  const isRTL = locale === 'he';
  const namerUIName = locale === 'he' ? 'נמר UI' : 'Namer UI';

  const madeByText: Record<string, LanguageStrings> = {
    en: { line: [ { text: `${t('footer.madeBy')} `, isLink: false }, { text: "Maxim Bortnikov", isLink: true, link: { href: "https://maxim-bortnikov.netlify.app/", text: "Maxim Bortnikov" } }, { text: ` ${t('footer.using')} `, isLink: false }, { text: "Next.js", isLink: true, link: { href: "https://nextjs.org/", text: "Next.js" } }, { text: ", ", isLink: false }, { text: "Perplexity", isLink: true, link: { href: "https://www.perplexity.ai/", text: "Perplexity" } }, { text: ", ", isLink: false }, { text: t('footer.and'), isLink: false }, { text: "Firebase Studio", isLink: true, link: { href: "https://firebase.studio/", text: "Firebase Studio" } } ]},
    he: {
      line: [
        { text: `${t('footer.madeBy')} `, isLink: false },
        { text: "מקסים בורטניקוב", isLink: true, link: { href: "https://maxim-bortnikov.netlify.app/", text: "מקסים בורטניקוב" } },
        { text: ` ${t('footer.using')} `, isLink: false },
        { text: "Perplexity", isLink: true, link: { href: "https://www.perplexity.ai/", text: "Perplexity" } },
        { text: " ,", isLink: false },
        { text: "Next.js", isLink: true, link: { href: "https://nextjs.org/", text: "Next.js" } },
        { text: ", ו", isLink: false },
        { text: "פיירבייס סטודיו", isLink: true, link: { href: "https://firebase.studio/", text: "פיירבייס סטודיו" } }
      ]
    },
    it: { line: [ { text: `${t('footer.madeBy')} `, isLink: false }, { text: "Maxim Bortnikov", isLink: true, link: { href: "https://maxim-bortnikov.netlify.app/", text: "Maxim Bortnikov" } }, { text: ` ${t('footer.using')} `, isLink: false }, { text: "Next.js", isLink: true, link: { href: "https://nextjs.org/", text: "Next.js" } }, { text: ", ", isLink: false }, { text: "Perplexity", isLink: true, link: { href: "https://www.perplexity.ai/", text: "Perplexity" } }, { text: ", ", isLink: false }, { text: t('footer.and'), isLink: false }, { text: "Firebase Studio", isLink: true, link: { href: "https://firebase.studio/", text: "Firebase Studio" } } ]},
    es: { line: [ { text: `${t('footer.madeBy')} `, isLink: false }, { text: "Maxim Bortnikov", isLink: true, link: { href: "https://maxim-bortnikov.netlify.app/", text: "Maxim Bortnikov" } }, { text: ` ${t('footer.using')} `, isLink: false }, { text: "Next.js", isLink: true, link: { href: "https://nextjs.org/", text: "Next.js" } }, { text: ", ", isLink: false }, { text: "Perplexity", isLink: true, link: { href: "https://www.perplexity.ai/", text: "Perplexity" } }, { text: ", ", isLink: false }, { text: t('footer.and'), isLink: false }, { text: "Firebase Studio", isLink: true, link: { href: "https://firebase.studio/", text: "Firebase Studio" } } ]},
  };

  const renderTextParts = (parts: TextPart[]) =>
    parts.map((part, index) =>
      part.isLink && part.link && sanitizeUrl(part.link.href) ? (
        <a
          key={index}
          href={sanitizeUrl(part.link.href) || "#"}
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary hover:underline"
        >
          {part.link.text}
        </a>
      ) : (
        <span key={index}>{part.text}</span>
      )
    );

  const currentLangStrings = madeByText[locale as keyof typeof madeByText] || madeByText.en;

  return (
    <Card>
        <CardContent className="p-4 text-center text-muted-foreground flex flex-col items-center gap-4">
            <Credits />
            <Separator />
             <NamerUiBadge 
                isRTL={isRTL} 
                poweredByText={intl.formatMessage({id: 'footer.poweredBy'})} 
                namerUIName={namerUIName}
             />
              <p className="break-words text-[13.8px]" style={{ wordBreak: 'break-word' }}>
                {renderTextParts(currentLangStrings.line)}
              </p>
        </CardContent>
    </Card>
  );
}